{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stategraph.fullname" . }}-postgres
  labels:
    {{- include "stategraph.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "stategraph.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
